# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AquaticPlantsDetector
                                 A QGIS plugin
 This plugin will be part of a workflow that will allow the user to detect aquatic plants in a body of water from satellite images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-01
        copyright            : (C) 2025 by Liam Messier & Jeremy Tem
        email                : Liam.Messier@Usherbrooke.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Liam Messier & Jeremy Tem'
__date__ = '2025-04-01'
__copyright__ = '(C) 2025 by Liam Messier & Jeremy Tem'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AquaticPlantsDetector class from file AquaticPlantsDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aquatic_plants_detector import AquaticPlantsDetectorPlugin
    return AquaticPlantsDetectorPlugin()
